version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform: Any CPU
before_build:
- cmd: nuget restore OnionConsole\OnionConsole.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
# workaround: http://help.appveyor.com/discussions/problems/8215-cannot-publish-to-nuget-get-400-bad-request-error
# deploy:
#  provider: NuGet
#  api_key:
#    secure: AR/eyg05Ehbf5+QQm6KTL6psHvQfW8j0G5CBJxBaO4tFa7XpHNzIHHDtn4M/mcey
#  artifact: /.*\.nupkg/
environment:
  api_key:
    secure: AR/eyg05Ehbf5+QQm6KTL6psHvQfW8j0G5CBJxBaO4tFa7XpHNzIHHDtn4M/mcey
deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key; if ($lastexitcode -ne 0) {throw}}
