version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform: Any CPU
before_build:
- cmd: nuget restore OnionConsole\OnionConsole.sln
build:
  publish_nuget: true
  include_nuget_references: false
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: AR/eyg05Ehbf5+QQm6KTL6psHvQfW8j0G5CBJxBaO4tFa7XpHNzIHHDtn4M/mcey
  artifact: /.*\.nupkg/
